#!/usr/bin/env bash
# Step 6: Ignore & Auto — Controlling the Mapper
set -euo pipefail

here="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${here}/_common.sh"

header "Step 6: Ignore & Auto — Controlling the Mapper"

info "The 'ignore' section skips target fields you don't want to map."
info "The 'auto' section contains auto-matched fields from 'suggest'."
echo ""

# Setup stage directory
stage_dir=$(setup_stage "step6")
out_dir="${stage_dir}/generated"
mkdir -p "$out_dir"

subheader "1. The ignore section"

cat > "${stage_dir}/mapping.yaml" << 'EOF'
version: "1"

mappings:
  - source: caster-generator/step-by-step/tutorial.APIProduct
    target: caster-generator/step-by-step/tutorial.DomainProduct

    "121":
      ProductID: SKU
      ProductName: Name
      InStock: Stock
      Category: CategoryTag

    # Ignore these target fields - they'll be set elsewhere
    ignore:
      - ID           # Auto-generated by database
      - PriceCents   # Will handle separately
      - CreatedAt    # Set by ORM
      - UpdatedAt    # Set by ORM
EOF

show_yaml "${stage_dir}/mapping.yaml" "Using ignore section:"

info "Ignored fields won't appear in the generated code."
info "Use ignore for:"
info "  • Database auto-generated fields (ID, timestamps)"
info "  • Fields set by other means (hooks, middleware)"

prompt_continue

subheader "2. Generate code with ignores"

run_cg gen \
    -mapping "${stage_dir}/mapping.yaml" \
    -out "$out_dir" \
    -pkg ./step-by-step/tutorial \
    -package casters

for f in "$out_dir"/*.go; do
    if [[ -f "$f" ]]; then
        show_go "$f" "Generated code (ignored fields not present):"
    fi
done

prompt_continue

subheader "3. The auto section (from suggest)"

info "Let's use 'suggest' and see what auto-matches it finds."
echo ""

run_cg suggest \
    -pkg ./step-by-step/tutorial \
    -from "caster-generator/step-by-step/tutorial.APIAddress" \
    -to "caster-generator/step-by-step/tutorial.DomainAddress" \
    -out "${stage_dir}/suggested.yaml"

show_yaml "${stage_dir}/suggested.yaml" "Suggested mapping with auto section:"

info "The 'auto' section contains suggestions with confidence scores."
info "These are auto-matched — you typically don't write them manually."

prompt_continue

subheader "4. Improving suggestions"

info "You can add explicit mappings and re-run suggest to improve them."
echo ""

# Create a partial mapping
cat > "${stage_dir}/partial.yaml" << 'EOF'
version: "1"

mappings:
  - source: caster-generator/step-by-step/tutorial.APIAddress
    target: caster-generator/step-by-step/tutorial.DomainAddress
    "121":
      ZipCode: PostalCode   # Explicit rename
EOF

info "Partial mapping with one explicit field:"
show_yaml "${stage_dir}/partial.yaml"

# Run suggest with existing mapping to improve
run_cg suggest \
    -pkg ./step-by-step/tutorial \
    -mapping "${stage_dir}/partial.yaml" \
    -out "${stage_dir}/improved.yaml"

show_yaml "${stage_dir}/improved.yaml" "Improved mapping (121 preserved, auto filled in):"

done_step "6"
info "Files are in: ${stage_dir}/"
info "Next: ./step7.sh — Transform basics for type mismatches"
