#!/usr/bin/env bash
set -euo pipefail

here="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# shellcheck source=../_scripts/common.sh
source "${here}/../_scripts/common.sh"

# ============================================================================
# Nested Example: Full-feature mapping workflow
# ============================================================================
# Types: nested.APIOrder -> nested.DomainOrder
#        nested.APICustomer -> nested.DomainCustomer
#        nested.APIItem -> nested.DomainLineItem
#        nested.APIAddress -> nested.DomainAddress
#
# Goal: Demonstrate nesting, requires, transforms, ignore, and auto sections
# ============================================================================

scenario_init "Nested" "Full-feature mapping: nesting, requires, transforms, ignore, auto"

# Directories
stages_dir="${here}/stages"
out_dir="${here}/generated"
clean_dir "$stages_dir"
clean_dir "$out_dir"

# ============================================================================
# Stage 1: Initial suggest for root type pair
# ============================================================================
stage_start "Initial Suggest" "Generate base mapping for APIOrder -> DomainOrder"

run_suggest "${stages_dir}/stage1.yaml" \
  -pkg ./examples/nested-struct \
  -from "caster-generator/examples/nested-struct.APIOrder" \
  -to "caster-generator/examples/nested-struct.DomainOrder" \
  -min-confidence 0.5

show_yaml_with_comments "${stages_dir}/stage1.yaml" \
  "Initial suggestions - notice nested types and potential issues"

info "Key observations:"
echo "  • ID (string) -> OrderID (uint) needs transform"
echo "  • Items -> LineItems needs dive hint"
echo "  • Shipping -> ShippingAddr is a nested pointer mapping"
echo "  • Nested types (Customer, Item, Address) need their own mappings"
echo ""

prompt_continue

# ============================================================================
# Stage 2: Patch YAML with structural corrections
# ============================================================================
stage_start "Patch YAML" "Add dive hints, ignores, and structural mappings"

cat > "${stages_dir}/stage2.yaml" << 'EOF'
version: "1"

# Transform function declarations
transforms:
  - name: nested_struct.StringToUint
    signature: "func(s string) uint"
  - name: nested_struct.FloatToCents
    signature: "func(price float64) int64"

mappings:
  # Root mapping: APIOrder -> DomainOrder
  - source: caster-generator/examples/nested-struct.APIOrder
    target: caster-generator/examples/nested-struct.DomainOrder
    fields:
      # ID string -> OrderID uint needs transform
      - source: ID
        target: OrderID
        transform: nested_struct.StringToUint
      # Items -> LineItems with dive for slice element conversion; pass OrderID down
      - source:
          Items: dive
        target:
          LineItems: dive
        extra:
          - name: OrderID
            def:
              target: OrderID
    auto:
      # These nested types will auto-resolve to their own mappings
      - source: Customer
        target: Customer
      - source: CreatedAt
        target: OrderedAt
      - source: Status
        target: OrderStatus
    ignore:
      # Shipping -> ShippingAddr is complex; handle separately or ignore
      - ShippingAddr

  # Customer mapping
  - source: caster-generator/examples/nested-struct.APICustomer
    target: caster-generator/examples/nested-struct.DomainCustomer
    fields:
      - source: ID
        target: CustomerID
        transform: nested_struct.StringToUint
    121:
      Email: EmailAddress
      Name: FullName
      Phone: PhoneNumber

  # Line item mapping with requires (receives OrderID from parent)
  - source: caster-generator/examples/nested-struct.APIItem
    target: caster-generator/examples/nested-struct.DomainLineItem
    requires:
      - name: OrderID
        type: uint
    fields:
      - source: OrderID
        target: OrderID
        transform: OrderID2OrderID
      - source: UnitPrice
        target: PriceCents
        transform: nested_struct.FloatToCents
    121:
      SKU: ProductSKU
      Name: ProductName
      Quantity: Qty
    ignore:
      # ID on DomainLineItem is auto-generated by ORM
      - ID
EOF

show_yaml_with_comments "${stages_dir}/stage2.yaml" \
  "Structured mapping with transforms, requires, dive hints"

info "Key additions:"
echo "  • Transform declarations for StringToUint and FloatToCents"
echo "  • dive hint on Items -> LineItems"
echo "  • requires section for LineItem (receives OrderID from parent)"
echo "  • ignore sections for unmapped fields"
echo ""

prompt_continue

# ============================================================================
# Stage 3: Suggest improve with our mapping
# ============================================================================
stage_start "Suggest Improve" "Run suggest to validate and fill in remaining mappings"

run_suggest_improve "${stages_dir}/stage2.yaml" "${stages_dir}/stage3.yaml" \
  -pkg ./examples/nested-struct \
  -min-confidence 0.5

show_yaml_with_comments "${stages_dir}/stage3.yaml" \
  "Improved mapping with additional suggestions"

prompt_continue

# ============================================================================
# Stage 4: Generate transform stubs
# ============================================================================
stage_start "Generate Transforms" "Create Go file with transform function implementations"

cat > "${here}/transforms.go" << 'EOF'
package nested_struct

import (
	"strconv"
)

// StringToUint converts a string ID to uint.
func StringToUint(s string) uint {
	v, err := strconv.ParseUint(s, 10, 64)
	if err != nil {
		// In production, handle this error appropriately
		return 0
	}
	return uint(v)
}

// FloatToCents converts a dollar amount (float64) to cents (int64).
func FloatToCents(price float64) int64 {
	return int64(price * 100)
}
EOF

show_file "${here}/transforms.go" "Transform implementations"

stage_done "Transform functions created"

prompt_continue

# ============================================================================
# Stage 5: Try generate (may need more fixes)
# ============================================================================
stage_start "Generate with Suggestions" "Generate code and capture any needed suggestions"

# Use stage2.yaml which has the transforms section
run_gen_with_suggestions "${stages_dir}/stage2.yaml" "$out_dir" "${stages_dir}/stage5_suggestions.yaml" \
  -pkg ./examples/nested-struct \
  -package casters

if [[ -f "${stages_dir}/stage5_suggestions.yaml" ]]; then
  show_yaml_with_comments "${stages_dir}/stage5_suggestions.yaml" \
    "Suggestions from generator (may include additional transforms needed)"
fi

info "Generated files:"
ls -la "$out_dir" 2>/dev/null || echo "(no files generated yet)"

prompt_continue

# ============================================================================
# Stage 6: Final generate
# ============================================================================
stage_start "Final Generate" "Generate final caster code"

# Use the stage2 file which has the transforms section
final_mapping="${stages_dir}/stage2.yaml"

run_gen "$final_mapping" "$out_dir" \
  -pkg ./examples/nested-struct \
  -package casters || {
    warn "Generation had issues - check the output above"
    prompt_continue
  }

info "Generated files:"
ls -la "$out_dir" 2>/dev/null || echo "(no files generated)"

prompt_continue

# ============================================================================
# Stage 7: Compile check
# ============================================================================
stage_start "Compile Check" "Verify generated code compiles"

test_compile ./examples/nested-struct || {
  warn "Compile check failed - may need additional transforms or fixes"
  scenario_partial "Review the errors above and implement missing transforms"
  exit 0
}

# ============================================================================
# Done
# ============================================================================
scenario_success

info "Final mapping: ${final_mapping}"
info "Transform functions: ${here}/transforms.go"
info "Generated casters: ${out_dir}/"
