// Code generated by "stringer -type=KindEnum -output=kind_string.go"; DO NOT EDIT.

package primitive

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[KindInt-1]
	_ = x[KindInt8-2]
	_ = x[KindInt16-3]
	_ = x[KindInt32-4]
	_ = x[KindInt64-5]
	_ = x[KindUint-6]
	_ = x[KindUint8-7]
	_ = x[KindUint16-8]
	_ = x[KindUint32-9]
	_ = x[KindUint64-10]
	_ = x[KindFloat32-11]
	_ = x[KindFloat64-12]
	_ = x[KindBool-13]
	_ = x[KindString-14]
	_ = x[KindTime-15]
	_ = x[KindDuration-16]
	_ = x[KindPrimitiveEnum-17]
}

const _KindEnum_name = "KindIntKindInt8KindInt16KindInt32KindInt64KindUintKindUint8KindUint16KindUint32KindUint64KindFloat32KindFloat64KindBoolKindStringKindTimeKindDurationKindPrimitiveEnum"

var _KindEnum_index = [...]uint8{0, 7, 15, 24, 33, 42, 50, 59, 69, 79, 89, 100, 111, 119, 129, 137, 149, 166}

func (i KindEnum) String() string {
	i -= 1
	if i < 0 || i >= KindEnum(len(_KindEnum_index)-1) {
		return "KindEnum(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _KindEnum_name[_KindEnum_index[i]:_KindEnum_index[i+1]]
}
